#!/bin/sh

unset DB_ENV_MYSQL_PASSWORD DB_ENV_MYSQL_ROOT_PASSWORD
unset MYSQL_PASSWORD MYSQL_ROOT_PASSWORD
unset DB_ENV_MYSQL_USER

unset ADMIN_PASSWORD

unset EMAIL_HOST EMAIL_HOST_USER EMAIL_HOST_PASSWORD
